### ISSUE TITLE
Issue with using spring datamock

### ISSUE THREAD

**Issue by SateeshBheemsetty** [mmnaseri/spring-data-mock#142] opened 2016-09-01 18:32 UTC
I read the article of spring data mock and thanks for providing it. i tried to introduce it into my project but when i try running test method i am getting exception:

From the internet, i understand the issue is with spring related jars. i have opened and verified that the 
 method mentioned error log is available. i am using spring 4.1.4 version i.e. spring test 4.1.4,spring data mock 1.1.4, spring core 4.1.4. i am not able to understand where exactly i am missing. could you please help me in getting resolved issue.

This Issue resolved by upgrading to spring latest version

**Comment by SateeshBheemsetty** [comment] 2016-09-06 18:07
This issue is resolved now by upgrading spring to latest versions. I am able to write tests for simple repo classes but i am failing to fix when my repository class contains queries like findByMinOrder, findByStatusCount etc.  i am looking for some help. please let me know if this is suitable for this kind of repository implementations. please suggest

**Comment by mmnaseri** [comment] 2016-09-07 02:35
Hi
I am glad that the problem is resolved. Can you include some code?
Does your `findByMinOrder` method look like this?

````java
public interface SomethingRepository {

    List<?> findByMinOrder(Object minOrder);

}
````

**Comment by SateeshBheemsetty** [comment] 2016-09-07 15:13
From my understanding, it is failing at all custom query implementation places it may be by MinOrder queries or it may count queries

**Comment by mmnaseri** [comment] 2016-09-08 00:57
I see. Well, custom implementations obviously need to have a custom implementation method for test. You can do that by writing a custom implementation for your methods. For example, if I had a dataset and I wanted to find the object whose `order` is minimum, this would be a crude implementation:

````java
public class MyMinOrderImpl implements DataStoreAware<MyObject, String> {
    
    private DataStore<String, MyObject> dataStore;

    @Override
    public void setDataStore(DataStore<String, MyObject> store) {
        dataStore = store;
    }

    public MyObject findByMinOrder() {
        final List<MyObject> all  = new ArrayList<>(dataStore.retrieveAll());
        Collections.sort(all, new Comparator<MyObject>() {
            @Override
            public int compare(MyObject first, MyObject second) {
                return first.getOrder().compareTo(second.getOrder());
            }
        });
    }

}
````

Once you have this implementation, you can plug it in your repository by using the DSL:

````java
final MyObjectRepository repository = RepositoryFactoryBuilder.builder()
                                                                        .usingImplementation(MyMinOrderImpl.class)
                                                                        .mock(MyObjectRepository.class);
````

Now, calls to `repository.findByMinOrder()` will be redirected to your method instead.

**Comment by mmnaseri** [comment] 2016-12-09 20:56
Since it has been three months and there is no feedback on this issue, I will close it for now.

**Closed by mmnaseri** 2016-12-09 20:56 UTC
Labels: pending–feedback
