### ISSUE TITLE
IN/IsIN Operator Not Supported ?

### ISSUE THREAD

**Issue by snc43** [mmnaseri/spring-data-mock#154] opened 2017-10-09 19:34 UTC
Hi, 
Based on [Operator Documentation](https://mmnaseri.github.io/spring-data-mock/site/#/readme#the-operators) when we try to Mock [Spring Repository-Query-Keywords](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repository-query-keywords) methods we found multiple methods are not supported. 

For example:
`
List<Person> findByPersonNumberIsIn(String[] numbers)
`
We get an empty List<Person>. Further reviewing the source code, we did not see any appropriate DataFunction or QueryDescriptor implementation. Please let us know if our understanding is correct and we have to Develop these to support the Repository-Query-Keywords.

**Comment by mmnaseri** [comment] 2018-07-26 21:00
Closing this as a duplicate of #153. But essentially yes, that is what needs to be done. This is a part I seem to have left out of the original implementation.

**Closed by mmnaseri** 2018-07-26 21:00 UTC
Labels: bug, duplicate
