### ISSUE TITLE
Code question: why there is need for spring-data-mock-build ?

### ISSUE THREAD

**Issue by paulvi** [mmnaseri/spring-data-mock#81] opened 2016-06-12 06:43 UTC
why there is need for spring-data-mock-build ?

I see it only redefines some properties for `spring-data-mock`

well, it may be needed when there is `spring-data-mock-samples` #79

**Comment by mmnaseri** [comment] 2016-06-12 07:39
Duplicate of #79

**Closed by mmnaseri** 2016-06-12 07:39 UTC
Labels: duplicate

**Comment by paulvi** [comment] 2016-06-12 08:11
well, actually answered in #25
